import type { SeoConfig } from '@pockly/shared';

const BASE_URL = 'https://json.pockly.uk';
const OG_IMAGE = `${BASE_URL}/og-image.png`;

export const jsonSeoConfig: SeoConfig = {
  baseUrl: BASE_URL,
  ogImage: OG_IMAGE,
  siteName: 'Pockly JSON Tools',
  applicationCategory: 'DeveloperApplication',
  pageConfigs: {
    '': {
      title: 'JSON Tools - Free Online JSON Utilities',
      description: 'Free online JSON tools: generator, formatter, validator, converter (CSV, XML, YAML), templates, and utilities. No installation required.',
      keywords: 'json tools, json generator, json formatter, json validator, json converter',
      ogImage: OG_IMAGE,
      canonicalUrl: BASE_URL,
    },
    generator: {
      title: 'JSON Generator - Create and Format JSON Online',
      description: 'Free online JSON generator and formatter. Create, validate, and format JSON structures with smart presets. Export as file or code.',
      keywords: 'json generator, json formatter, json validator, create json',
      ogImage: OG_IMAGE,
      canonicalUrl: `${BASE_URL}/generator`,
    },
    templates: {
      title: 'JSON Templates - Ready-to-Use JSON Examples',
      description: 'Free JSON templates for common use cases. API templates, configurations, data structures. Copy and customize.',
      keywords: 'json templates, json examples, json presets',
      ogImage: OG_IMAGE,
      canonicalUrl: `${BASE_URL}/templates`,
    },
    convert: {
      title: 'JSON Convert - Convert JSON to CSV XML YAML TSV',
      description: 'Convert JSON to CSV, TSV, XML, YAML and vice versa. Free online JSON converter tool.',
      keywords: 'json to csv, json to xml, json to yaml, json converter',
      ogImage: OG_IMAGE,
      canonicalUrl: `${BASE_URL}/convert`,
    },
    'convert/csv-to-json': {
      title: 'CSV to JSON Converter - Convert CSV to JSON Online',
      description: 'Convert CSV files to JSON online. Free and fast CSV to JSON converter. No installation required.',
      keywords: 'csv to json, csv converter, csv to json online',
      ogImage: OG_IMAGE,
      canonicalUrl: `${BASE_URL}/convert/csv-to-json`,
    },
    'convert/tsv-to-json': {
      title: 'TSV to JSON Converter - Convert TSV to JSON Online',
      description: 'Convert TSV files to JSON online. Free and fast TSV to JSON converter.',
      keywords: 'tsv to json, tsv converter, tsv to json online',
      ogImage: OG_IMAGE,
      canonicalUrl: `${BASE_URL}/convert/tsv-to-json`,
    },
    'convert/json-to-csv': {
      title: 'JSON to CSV Converter - Convert JSON to CSV Online',
      description: 'Convert JSON to CSV format online. Free and fast JSON to CSV converter. Download as CSV file.',
      keywords: 'json to csv, json converter, json to csv online',
      ogImage: OG_IMAGE,
      canonicalUrl: `${BASE_URL}/convert/json-to-csv`,
    },
    'convert/json-to-tsv': {
      title: 'JSON to TSV Converter - Convert JSON to TSV Online',
      description: 'Convert JSON to TSV format online. Free and fast JSON to TSV converter.',
      keywords: 'json to tsv, json to tsv converter',
      ogImage: OG_IMAGE,
      canonicalUrl: `${BASE_URL}/convert/json-to-tsv`,
    },
    'convert/json-to-xml': {
      title: 'JSON to XML Converter - Convert JSON to XML Online',
      description: 'Convert JSON to XML format online. Free and fast JSON to XML converter.',
      keywords: 'json to xml, json to xml converter',
      ogImage: OG_IMAGE,
      canonicalUrl: `${BASE_URL}/convert/json-to-xml`,
    },
    'convert/json-to-yaml': {
      title: 'JSON to YAML Converter - Convert JSON to YAML Online',
      description: 'Convert JSON to YAML format online. Free and fast JSON to YAML converter.',
      keywords: 'json to yaml, json to yaml converter',
      ogImage: OG_IMAGE,
      canonicalUrl: `${BASE_URL}/convert/json-to-yaml`,
    },
    utils: {
      title: 'JSON Utils - Validate Minify Sort Format',
      description: 'JSON utilities: validate, minify, prettify, sort keys, flatten, unflatten, diff, and query. Free online JSON tools.',
      keywords: 'json validate, json minify, json prettify, json sort',
      ogImage: OG_IMAGE,
      canonicalUrl: `${BASE_URL}/utils`,
    },
    'utils/format': {
      title: 'JSON Format - Prettify JSON Online',
      description: 'Prettify and format JSON online. Indent and beautify JSON structures. Free JSON formatter tool.',
      keywords: 'json format, json prettify, json beautify',
      ogImage: OG_IMAGE,
      canonicalUrl: `${BASE_URL}/utils/format`,
    },
    'utils/minify': {
      title: 'JSON Minify - Minify JSON Online',
      description: 'Minify JSON online. Remove whitespace and compress JSON files. Free JSON minifier.',
      keywords: 'json minify, json compress, minify json',
      ogImage: OG_IMAGE,
      canonicalUrl: `${BASE_URL}/utils/minify`,
    },
    'utils/sort': {
      title: 'JSON Sort - Sort JSON Keys Online',
      description: 'Sort JSON keys alphabetically online. Reorder JSON object keys. Free JSON sort tool.',
      keywords: 'json sort, sort json keys, json order',
      ogImage: OG_IMAGE,
      canonicalUrl: `${BASE_URL}/utils/sort`,
    },
    'utils/validate': {
      title: 'JSON Validator - Validate JSON Online',
      description: 'Validate JSON online. Check JSON syntax and structure. Free JSON validator tool.',
      keywords: 'json validator, json validate, json check',
      ogImage: OG_IMAGE,
      canonicalUrl: `${BASE_URL}/utils/validate`,
    },
    'utils/flatten': {
      title: 'JSON Flatten - Flatten Nested JSON Online',
      description: 'Flatten nested JSON objects online. Convert deep JSON structures to flat key-value pairs. Free JSON flatten tool.',
      keywords: 'json flatten, flatten json, nested json',
      ogImage: OG_IMAGE,
      canonicalUrl: `${BASE_URL}/utils/flatten`,
    },
    'utils/unflatten': {
      title: 'JSON Unflatten - Unflatten JSON Online',
      description: 'Unflatten flat key-value JSON back to nested objects. Free JSON unflatten tool.',
      keywords: 'json unflatten, unflatten json',
      ogImage: OG_IMAGE,
      canonicalUrl: `${BASE_URL}/utils/unflatten`,
    },
    'utils/diff': {
      title: 'JSON Diff - Compare JSON Online',
      description: 'Compare two JSON documents side-by-side. Find differences between JSON structures. Free JSON diff tool.',
      keywords: 'json diff, json compare, json difference',
      ogImage: OG_IMAGE,
      canonicalUrl: `${BASE_URL}/utils/diff`,
    },
    'utils/query': {
      title: 'JSON Query - Query JSON with JSONPath',
      description: 'Query JSON data using JSONPath expressions. Extract values from complex JSON. Free JSON query tool.',
      keywords: 'json query, jsonpath, json extract',
      ogImage: OG_IMAGE,
      canonicalUrl: `${BASE_URL}/utils/query`,
    },
  '404': {
    title: 'Page Not Found - Pockly JSON Tools',
    description: 'The page you are looking for does not exist.',
    noindex: true,
  },
  // Spanish pages (/es/...)
  'es': {
    title: 'Herramientas JSON Online Gratis - Formatear, Validar, Convertir',
    description: 'Herramientas JSON online gratis: generador, formateador, validador, conversor (CSV, XML, YAML), plantillas y utilidades. Sin instalación.',
    keywords: 'herramientas json, formatear json, validar json, convertir json',
    ogImage: OG_IMAGE,
    canonicalUrl: `${BASE_URL}/es`,
  },
  'es/generator': {
    title: 'Generador de JSON - Crear y Formatear JSON Online',
    description: 'Generador y formateador de JSON online gratis. Crea, valida y formatea estructuras JSON con presets inteligentes. Exporta como archivo o código.',
    keywords: 'generador json, crear json, formateador json',
    ogImage: OG_IMAGE,
    canonicalUrl: `${BASE_URL}/es/generator`,
  },
  'es/templates': {
    title: 'Plantillas JSON - Ejemplos Listos para Usar',
    description: 'Plantillas JSON gratis para casos comunes. Plantillas de API, configuraciones y estructuras de datos. Copia y personaliza.',
    keywords: 'plantillas json, ejemplos json',
    ogImage: OG_IMAGE,
    canonicalUrl: `${BASE_URL}/es/templates`,
  },
  'es/convert': {
    title: 'Convertir JSON - JSON a CSV, XML, YAML, TSV',
    description: 'Convierte JSON a CSV, TSV, XML, YAML y viceversa. Conversor de JSON online gratis.',
    keywords: 'json a csv, json a xml, json a yaml, conversor json',
    ogImage: OG_IMAGE,
    canonicalUrl: `${BASE_URL}/es/convert`,
  },
  'es/convert/csv-to-json': {
    title: 'Conversor CSV a JSON - Convertir CSV a JSON Online',
    description: 'Convierte archivos CSV a JSON online. Conversor CSV a JSON rápido y gratis. Sin instalación.',
    keywords: 'csv a json, convertir csv, conversor csv',
    ogImage: OG_IMAGE,
    canonicalUrl: `${BASE_URL}/es/convert/csv-to-json`,
  },
  'es/convert/tsv-to-json': {
    title: 'Conversor TSV a JSON - Convertir TSV a JSON Online',
    description: 'Convierte archivos TSV a JSON online. Conversor TSV a JSON rápido y gratis.',
    keywords: 'tsv a json, convertir tsv',
    ogImage: OG_IMAGE,
    canonicalUrl: `${BASE_URL}/es/convert/tsv-to-json`,
  },
  'es/convert/json-to-csv': {
    title: 'Conversor JSON a CSV - Convertir JSON a CSV Online',
    description: 'Convierte JSON a formato CSV online. Conversor JSON a CSV rápido y gratis. Descarga como archivo CSV.',
    keywords: 'json a csv, convertir json, exportar csv',
    ogImage: OG_IMAGE,
    canonicalUrl: `${BASE_URL}/es/convert/json-to-csv`,
  },
  'es/convert/json-to-tsv': {
    title: 'Conversor JSON a TSV - Convertir JSON a TSV Online',
    description: 'Convierte JSON a formato TSV online. Conversor JSON a TSV rápido y gratis.',
    keywords: 'json a tsv, convertir json',
    ogImage: OG_IMAGE,
    canonicalUrl: `${BASE_URL}/es/convert/json-to-tsv`,
  },
  'es/convert/json-to-xml': {
    title: 'Conversor JSON a XML - Convertir JSON a XML Online',
    description: 'Convierte JSON a formato XML online. Conversor JSON a XML rápido y gratis.',
    keywords: 'json a xml, convertir json a xml',
    ogImage: OG_IMAGE,
    canonicalUrl: `${BASE_URL}/es/convert/json-to-xml`,
  },
  'es/convert/json-to-yaml': {
    title: 'Conversor JSON a YAML - Convertir JSON a YAML Online',
    description: 'Convierte JSON a formato YAML online. Conversor JSON a YAML rápido y gratis.',
    keywords: 'json a yaml, convertir json a yaml',
    ogImage: OG_IMAGE,
    canonicalUrl: `${BASE_URL}/es/convert/json-to-yaml`,
  },
  'es/utils': {
    title: 'Utilidades JSON - Validar, Minificar, Ordenar, Formatear',
    description: 'Utilidades JSON: validar, minificar, embellecer, ordenar claves, aplanar, comparar y consultar. Herramientas JSON online gratis.',
    keywords: 'validar json, minificar json, ordenar json',
    ogImage: OG_IMAGE,
    canonicalUrl: `${BASE_URL}/es/utils`,
  },
  'es/utils/format': {
    title: 'Formatear JSON Online - Embellecer JSON Gratis',
    description: 'Formatea y embellece JSON online. Indenta estructuras JSON. Formateador de JSON gratis.',
    keywords: 'formatear json, embellecer json, json pretty',
    ogImage: OG_IMAGE,
    canonicalUrl: `${BASE_URL}/es/utils/format`,
  },
  'es/utils/minify': {
    title: 'Minificar JSON Online Gratis',
    description: 'Minifica JSON online. Elimina espacios y comprime archivos JSON. Minificador de JSON gratis.',
    keywords: 'minificar json, comprimir json',
    ogImage: OG_IMAGE,
    canonicalUrl: `${BASE_URL}/es/utils/minify`,
  },
  'es/utils/sort': {
    title: 'Ordenar Claves JSON Online',
    description: 'Ordena las claves de un JSON alfabéticamente online. Reordena objetos JSON. Herramienta gratis.',
    keywords: 'ordenar json, ordenar claves json',
    ogImage: OG_IMAGE,
    canonicalUrl: `${BASE_URL}/es/utils/sort`,
  },
  'es/utils/validate': {
    title: 'Validador de JSON Online Gratis',
    description: 'Valida JSON online. Comprueba la sintaxis y estructura de tu JSON. Validador de JSON gratis.',
    keywords: 'validador json, validar json, comprobar json',
    ogImage: OG_IMAGE,
    canonicalUrl: `${BASE_URL}/es/utils/validate`,
  },
  'es/utils/flatten': {
    title: 'Aplanar JSON - Aplanar JSON Anidado Online',
    description: 'Aplana objetos JSON anidados online. Convierte estructuras profundas en pares clave-valor. Herramienta gratis.',
    keywords: 'aplanar json, json anidado',
    ogImage: OG_IMAGE,
    canonicalUrl: `${BASE_URL}/es/utils/flatten`,
  },
  'es/utils/unflatten': {
    title: 'Desaplanar JSON Online',
    description: 'Convierte JSON plano de pares clave-valor de vuelta a objetos anidados. Herramienta gratis.',
    keywords: 'desaplanar json, json anidado',
    ogImage: OG_IMAGE,
    canonicalUrl: `${BASE_URL}/es/utils/unflatten`,
  },
  'es/utils/diff': {
    title: 'Comparar JSON Online - Diff de JSON Gratis',
    description: 'Compara dos documentos JSON lado a lado. Encuentra diferencias entre estructuras JSON. Herramienta gratis.',
    keywords: 'comparar json, diff json, diferencias json',
    ogImage: OG_IMAGE,
    canonicalUrl: `${BASE_URL}/es/utils/diff`,
  },
  'es/utils/query': {
    title: 'Consultar JSON con JSONPath Online',
    description: 'Consulta datos JSON con expresiones JSONPath. Extrae valores de JSON complejos. Herramienta gratis.',
    keywords: 'consultar json, jsonpath, extraer json',
    ogImage: OG_IMAGE,
    canonicalUrl: `${BASE_URL}/es/utils/query`,
  },
  'es/404': {
    title: 'Página No Encontrada - Pockly JSON Tools',
    description: 'La página que buscas no existe.',
    noindex: true,
  },
  },
};
